name: Regression Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      #- name: Install Verilator requirements
        #run: |
          #sudo apt update -y
          #sudo apt-get install git help2man perl python3 make
          #sudo apt-get install g++  # Alternatively, clang
          #sudo apt-get install libfl-dev  # Ubuntu only (ignore if gives error)
          #sudo apt-get install zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)
      #- name: Set up Verilator
        #run: |
          #git clone https://github.com/verilator/verilator
          #cd verilator
          #git checkout stable
          #autoconf
          #./configure
          #make
          #sudo make install
        #shell: bash
      - name: Install Icarus and its requirements
        run: |
          sudo apt update
          sudo apt-get install build-essential libboost-dev iverilog
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install --upgrade nox

      - name: Run nox tests
        run: nox -s "run-${{ matrix.python-version }}"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
